language: ruby
dist: trusty

sudo: false

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages
    - '.rvm'

git:
  depth: false

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.9.3
  - nvm use 8.9.3

install:
  - yarn install
  - bundle install --jobs=3 --retry=3

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: develop
