language: ruby
dist: trusty

sudo: false

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages
    - '.rvm'
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

git:
  depth: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.9.3
  - nvm use 8.9.3

install:
  - yarn install
  - bundle install --jobs=3 --retry=3

script:
  - yarn build
  # - bundle exec rake check_html # Deliberately disabled for now

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: master
