language: ruby
dist: trusty

sudo: false

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

install:
  - yarn
  - bundle install --jobs=3 --retry=3

script:
  - yarn build

