###
# Build
###
source: src
destination: dist
timezone: Europe/London
incremental: true

###
# Collections
###
collections_dir: _collections
collections:
  user-group:
    output: true

###
# Default front matter
###

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: content-page

###
# Plugins
###
# plugins:
