###
# Build
###
source: src
destination: dist
timezone: Europe/London
incremental: true
permalink: pretty

exclude: ['_templates']
###
# Collections
###
collections_dir: _collections
collections:
  user-group:
    output: true

###
# Default front matter
###

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: content-page
      nav:
        order: 1000
###
# Plugins
###
plugins:
  - jekyll-git_metadata
