###
# Build
###
source: src
destination: dist
timezone: Europe/London
incremental: true
permalink: pretty

exclude: ['_templates']

###
# Meta
###
url: http://open-standards-guidebook.odi.kindclients.co.uk
name: Open Standards for Data Guidebook
twitter_username: ODIHQ
description: This is the default site description, change me
title_image: ''
ga: 'UA-XXXXXXXX-X' #@TODO - Add this...

###
# Collections
###
collections_dir: _collections
collections:
  user-group:
    output: true

###
# Default front matter
###

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: content-page
      nav:
        order: 1000
      show_toc: true
      show_nav: true
###
# Plugins
###
plugins:
  - jekyll-git_metadata
