title: "Home Page Layout"
status: "ready"

context:
  hero:
    heading: Open Standards Organisations
    breadcrumbs: false
    sidenav: true
    lowernav: false
  lede:
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar ex pretium interdum gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere.'

  navTitle: false
  nav:
    pill: true
    modifier: m-nav--large
    items:
    -
      title: What are Open Standards for Data?
    -
      title: Types of Open Data Standards
    -
      title: Why use Open Standards for Data
  metatitle: false

  pill: false

  sections:
    items:
    -
      title: Creating Open Standards
      meta: Process
      items:
      -
        title: Scoping & Starting
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Developing standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Governance and guidance
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Impact of Open Standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
    -
      title: Open Standards and you
      meta: Groups
      items:
      -
        title: Organisations developing standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Policy specialists
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Domain experts
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Data publishers and consumers
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.


