title: "Masthead"
status: "ready"
context:
    title: Open Standards for Data
    navitems:
        -
            title: Introduction
            active: false
        -
            title: Creating Impact
            active: true
        -
            title: Creating Open Standards
            active: false
        -
            title: The Standards Community
            active: false
