title: "Listing Page - Short Layout"
status: "ready"

context:
  hero:
    heading: false
    breadcrumbs: false
    sidenav: false
    lowernav: true

  navTitle: Introduction to Open Standards
  nav:
    modifier: m-nav--large
    items:
    -
      title: What are Open Standards for Data?
    -
      title: Types of Open Data Standards
    -
      title: Why use Open Standards for Data

  metatitle:
    message: Getting Started

  pill: false

  sections:
    items:
    -
      title: Creating Open Standards
      meta: Process
      items:
      -
        title: Scoping & Starting
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Developing standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Governance and guidance
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Impact of Open Standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
    -
      title: Open Standards and you
      meta: Groups
      items:
      -
        title: Organisations developing standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Policy specialists
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Domain experts
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Data publishers and consumers
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.

  lede:
    message: 'Some introductory text lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vulputate magna velit. Vestibulum fermentum fermentum libero. Vestibulum dui dui, pulvinar bibendum nulla eget, lacinia fermentum lorem.'
